[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}-{{slug title}}"
extension = "md"
template = "default.md"

id-charset = "alphanum"
id-length = 4
id-case = "lower"

[extra]
author = "Kobra"

[tool]
editor = "nvim"

[lsp]
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"

[alias]
rm = "zk list --interactive --quiet --format path --delimiter0 $@ | xargs -0 rm -vf --"
