git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding: # colemak
  universal:
    prevItem-alt: "e" # go one line up
    nextItem-alt: "n" # go one line down
    prevBlock-alt: "h" # goto the previous block / panel
    nextBlock-alt: "i" # goto the next block / panel
    nextMatch: "j"
    prevMatch: "J"
    new: "k"
    edit: "o"
    openFile: "O"
    scrollUpMain-alt1: "E" # main panel scroll up
    scrollDownMain-alt1: "N" # main panel scroll down
  files:
    ignoreFile: "I"
  branches:
    viewGitFlowOptions: "I"
    setUpstream: "U"
  commits:
    moveDownCommit: "<c-n>" # move commit down one
    moveUpCommit: "<c-e>" # move commit up one
  submodules:
    init: "I"
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim --line={{line}} {{filename}}"
  editAtLineAndWait: "nvim --block --line={{line}} {{filename}}"
  editInTerminal: true
