add_newline = false

format = """
$directory\
${custom.short_branch}\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$gcloud\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$shell\
$character"""

[character]
success_symbol = "[➜](bold green)"

[gcloud]
format = 'on [$active]($style) '

[custom.short_branch]
command = "short-branch"
when = "git rev-parse --is-inside-work-tree"
symbol = " "
style = "bold purple"
