format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$gcloud\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$shell\
$character"""

[character]
success_symbol = "[➜](bold green)"

[gcloud]
format = 'using [$symbol$active]($style) '
